### ISSUE TITLE
Can't able to use this module or directive?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [arkon/ng-click-outside#12]
Can't resolve all parameters for ClickOutsideDirective: ([object Object], ?)

First I import clickoutsidemodule and then use (clickoutside) event in div. But, it gives error.

**Comment by arkon** [comment]
Can I see how you're importing and using the module?

**Comment by sudhirroy-tudip** [comment]
import { ClickOutsideModule } from 'ng-click-outside';
And then import this module in @import decoration

**Comment by arkon** [comment]
@sudhirroy-tudip Do you mean in the `imports` array of your `NgModule`?

**Comment by sudhirroy-tudip** [comment]
Yes

**Comment by sudhirroy-tudip** [comment]
Also, the earlier version of the same module works well but when you guys updated it, It's no more working and says Can't resolve all parameters for ClickOutsideDirective: ([object Object], ?)

**Comment by arkon** [comment]
Did you also import the `BrowserModule` from `@angular/platform-browser`? The only other suggestion that I have would be to remove `node_modules` and install everything again in case something went wrong.

**Comment by sudhirroy-tudip** [comment]
No, I haven't import browser module.

**Comment by arkon** [comment]
Try importing it to see if that helps.
