### ISSUE TITLE
ClickOutsideModule not working inside an anchor

### ISSUE THREAD

**Issue by jacopolanzoni** [arkon/ng-click-outside#15]
I import ClickOutsideModule in the following module: 

`
@NgModule({
`
`
  imports: [ClickOutsideModule],
`
`
  declarations: [TopBarComponent, MyComponent]
`
`
})
`
`
export class TopBarModule { }
`

MyComponent is as follows:

`
@Component({
`
`
  moduleId: module.id,
`
`
  selector: 'my-component',
`
`
  styleUrls: ['my-component.css'],
`
`
  templateUrl: 'my-component.component.html'
`
`
})
`
`
export class MyComponent {
`
`
  public onClickedOutside(event: Event) {
`
`
    console.log('Clicked outside:', event);
`
`
  }
`
`
}
`

with the template being:

`
< ul (clickOutside)="onClickedOutside($event)">Hello</ul >
`

Nothing is printed on the console when I click outside the unsorted list.

**Comment by arkon** [comment]
Works fine for me. Only notable thing is that you can't have spaces in your tags (although that should've given you an error):

```html
<ul (clickOutside)="onClickedOutside($event)">Hello</ul>
```
