### ISSUE TITLE
Better info for using options

### ISSUE THREAD

**Issue by mikkoh85** [arkon/ng-click-outside#16]
Hi! 

I use this and found it useful, but I'd need to use some option to delay it so it wouldn't take the first click which opens the menu (which uses this to close itself). I found there is `delayClickOutsideInit`, but I have absolutely no idea where this option goes in my code and found no answers. Can you improve your readme file so that it tells where it should go?

**Comment by mikkoh85** [comment]
Alright, I found out that it needs to go to my element in html file like this: 
`<div *ngIf="menuVisible" (clickOutside)="hideMenu($event)" [delayClickOutsideInit]="true" 
		 (click)="hideMenu()">`
,but better info for other rookies would be good 👍

**Comment by arkon** [comment]
It's assumed that Angular developers already know [how to use directives](https://angular.io/guide/attribute-directives), but I'll just answer questions as needed instead of having overly verbose documentation. :)

**Comment by mikkoh85** [comment]
Another problem. When I'm running unit tests I get this error message: 
`Error: Template parse errors:
    Can't bind to 'delayClickOutsideInit' since it isn't a known property of 'div'. ("</i>
                </div>
                <div class="shadowed-box-content" *ngIf="menuVisible" (clickOutside)="hideMenu()" [ERROR ->][delayClickOutsideInit]="true" (cli
ck)="hideMenu()">`.
Am I missing something in my spec file or?
