### ISSUE TITLE
Does not work AOT

### ISSUE THREAD

**Issue by wildlifechorus** [arkon/ng-click-outside#17]
I get 

`TypeError: Cannot read property 'removeEventListener' of undefined`

Should be implemented with the following:

[https://medium.com/@zainzafar/localstorage-with-angular-universal-2a111fb4af72](https://medium.com/@zainzafar/localstorage-with-angular-universal-2a111fb4af72)

**Comment by wildlifechorus** [comment]
Made a fork and fixed it: [https://github.com/chippdnyc/ng-click-outside](https://github.com/chippdnyc/ng-click-outside)

**Comment by arkon** [comment]
A PR is welcome!

**Comment by wildlifechorus** [comment]
Done :)

**Comment by arkon** [comment]
Published in v3.0.0 (which now requires Angular 4+). Thanks @wildlifechorus !
