### ISSUE TITLE
Directive Does Not Work on IE10

### ISSUE THREAD

**Issue by dh-lex** [arkon/ng-click-outside#2]
I have tried my application that is using this directive as well as the sample page you have provided and both fail in IE 10. They give the error: `HTMLDocument is undefined`. I'm not sure what the exact intended browser support for this directive is but it would be awesome if it did work on IE 10.

**Comment by arkon** [comment]
Unfortunately, I don't have easy access to IE 10 right now. I did push out an update this morning to support AOT though, and that might also affect this. I've just redeployed the [demo site](https://echeung.me/ng2-click-outside/) with the latest version, so could you check that out in IE 10 to see if it works?

**Comment by dh-lex** [comment]
Unfortunately, it is still failing on IE10, see the image below. Just as an fyi, here is an easy way to test IE10 locally [IE VirtualBoxes](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

<img width="1021" alt="screen shot 2016-10-05 at 12 36 44 pm" src="https://cloud.githubusercontent.com/assets/20907799/19122429/703f0d5a-8af8-11e6-8459-50bd8b63bc3c.png">

**Comment by arkon** [comment]
@dh-lex `bundle.js` might be cached, so could you make sure you're getting the latest version? I'm fairly certain that `HTMLDocument` isn't referenced there anymore.

**Comment by dh-lex** [comment]
You are correct, I apologize for that inconvenience, I usually do not use IE for everyday use. It is now working as expected with the redeployed site, thank you!
