### ISSUE TITLE
Disabling directive

### ISSUE THREAD

**Issue by NagRock** [arkon/ng-click-outside#21]
Hey, first of all thanks for your work!
Is there any option to disable `clickOutside` temporary? For example parameter with `isEnabled` flag. I want to have `clickOutside` handler but remove it functionality in some cases.

**Comment by arkon** [comment]
Added `[clickOutsideEnabled]` in v3.1.0.

**Comment by NagRock** [comment]
Great news! Thanks. I will test it asap :)
