### ISSUE TITLE
databinding on load

### ISSUE THREAD

**Issue by SandyShiva** [arkon/ng-click-outside#24]
I have list from API POST,i want to bind on load,but it is not,when i click on my page after it loads then it shows the data,

My Compnetnt HTML

<header-component [userName]="getUserName()" [userLength]="getUserLength()" [userImage]="getUserImage()"></header-component>
<div class="container" style="margin-top:330px;">
    {{pageTitle}}
    <div class="row">
        <table>
            <thead>
                <tr>
                    <th>Number</th>
                    <th>Name</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let group of groups">
                    <td>{{group.logType}}</td>
                    <td>{{group.logType}}</td>
                    <td>{{group.logType}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

And my Component.ts
import { Component, OnInit } from '@angular/core';
import { Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { HeaderComponent } from '../header.component'
import { AuthenticationService } from '../Services/auth.service';
@Component({
    templateUrl: 'app/controlPannel/group.component.html'
})
export class groupComponent implements OnInit {
    pageTitle: string = 'Group Component';
    groups:any = [];
    constructor(
        private service : AuthenticationService
    ) {
        this.service.getGroupDetails().subscribe(res => { this.groups = res; console.log(this.groups) });
    }
    ngOnInit() {
        this.getUserName();
        this.getUserLength();
        this.getUserImage();
        this.pageTitle = 'On Loading';
        
    }
    getUserName(): string {
        return localStorage.getItem('userName');
    }
    getUserLength(): boolean {
        return true;
    }
    getUserImage(): string {
        return '../Images/' + localStorage.getItem('userImage');
    }
    getGroupDetails(): void {
        
    }
    
}

**Comment by arkon** [comment]
This is unrelated to this library. You can try asking this on StackOverflow.
