### ISSUE TITLE
Event fired as many times as instances

### ISSUE THREAD

**Issue by BenDevelopment** [arkon/ng-click-outside#3]
I you use the directive in many places on your page, the event is fired as many times as the number of uses in the page by each directive.

Here is an example:

```
<button (clickOutside)="onClickedOutside_A($event)">button A</button>
<button (clickOutside)="onClickedOutside_B($event)">button B</button>
```

```
onClickedOutside_A(event){
  alert("A");
}

onClickedOutside_B(event){
  alert("B");
}
```

The alert shows 4 times in this order: A, B, A, B.
It should only fire: A, B.

**Comment by BenDevelopment** [comment]
I didn't read the doc well ^^, attachOutsideOnClick do the trick :).

**Comment by arkon** [comment]
Actually, that could still be a bug. Are you saying that if you have those two buttons with their `clickOutside` directives, then clicking somewhere else (not on either of the two buttons), that it gives A,B,A,B?
