### ISSUE TITLE
Default value of 'attachOutsideOnClick'

### ISSUE THREAD

**Issue by psmyrdek** [arkon/ng-click-outside#30]
Hi,

I'd like to ask why `attachOutsideOnClick` property is by default set to false. In my app enabling this feature improved performance a lot, especially when I'm running hybrid app (two angulars) and each click on body fires the $digest in the part managed of AngularJS. With `attachOutsideOnClick` set to true all these problems are gone.

Btw great job!

**Comment by arkon** [comment]
Pretty much just because I added it in later and didn't want it to be a breaking change.
