### ISSUE TITLE
Fire event on window blur if page is visible

### ISSUE THREAD

**Issue by DanielKucal** [arkon/ng-click-outside#32]
If our page contains an iframe and user clicks on it - it is outside click, but web browser doesn't emit proper event due to security reasons. It would be great to have a work-around for it. I suggest to listen to window blur event and emit outside click event if page is visible like in the following example:

        window.addEventListener('blur', () => {
            setTimeout(() => {
                if (!document.hidden) {
                    console.log('outside click event');
                }
            });
        });

Let me know what you think, so I will prepare PR.

**Comment by DanielKucal** [comment]
@arkon, could you have a look at this topic?

**Comment by arkon** [comment]
Sounds reasonable. An option called `[emitOnBlur]` or something would make sense.
