### ISSUE TITLE
exclusion does not pick up popups or menus that are added to DOM much later.

### ISSUE THREAD

**Issue by zoofadoofa** [arkon/ng-click-outside#33]
Here is a demo showcasing the problem
https://stackblitz.com/edit/clickoutside-exclused-popup?file=app%2Fdatepicker-overview-example.html

I think its being caused by the fact that the query runs when clickOutside inits, but from what I can tell there isn't a way to make it aware of a popup or menu that appears later.

**Comment by arkon** [comment]
I'd need to check on an actual computer and not my phone, but I suspect the datepicker is being appended somewhere in the DOM outside of that expanded box.

**Comment by arkon** [comment]
Yeah, so I just checked and the date picker gets inserted outside of that container. *Technically* ng-click-outside is working as expected, but I'm not sure if there's a good workaround for you.

**Comment by zoofadoofa** [comment]
Right now I'm able to get around the issue by abusing clickOutsideEnabled and wiring that to the on open/close events for the datepicker. So I'm not roadblocked.

However, the clickOutside is techincally not working because I explicitly wrote exclusions for the datepicker, (see the typescript variable "exclusions"). Which has to do with 'when' the exclusions are queried. Which is on init of clickOutside.

I'm not sure that there would be a better way to detect or update the queried excluded DOM elements as that would still have to be wired up manually.

Maybe using clickOutsideEnabled is the answer.

**Comment by arkon** [comment]
Ah, you're right. It seems that it's _sort of_  working since it doesn't close when you just click somewhere in the datepicker. Maybe it's something to do with the submission of the datepicker?

**Comment by zoofadoofa** [comment]
Hey arkon, 
https://stackblitz.com/edit/clickoutside-exclude-delay?file=app%2Fexample.html

I put together a simple demo with just divs with one being added after a delay to see if it would pick it up and clickOutside seems to handle it just fine.

started looking at https://github.com/arkon/ng-click-outside/blob/master/src/click-outside.directive.ts#L99 during debug to see what nodes shows up, and in both demos it finds the nodes we expect. 

In demo1 I see all 30 days as nodes, and in demo2 I see the 2 divs init and delay.
I think your right about something with the submission of the datepicker.

I am going to close the issue as everything is working they way it should. I am unable to narrow down exactly what that calendar is doing that is causing it to ignore clickOutside.
