### ISSUE TITLE
Proposition: emit event on pressing ESC

### ISSUE THREAD

**Issue by DanielKucal** [arkon/ng-click-outside#35]
What do you think about adding `[emitOnEsc]` input?

**Comment by arkon** [comment]
As in pressing the `ESC` key on your keyboard?

**Comment by DanielKucal** [comment]
Exactly

**Comment by arkon** [comment]
No, that should be handled with a regular `(keypress)` handler. I'd rather not add that to this lib since it feels like bloat.

**Comment by DanielKucal** [comment]
Okay, if someone would need this too, I've created simple **[angular-esc](https://github.com/DanielKucal/angular-esc)** module.
