### ISSUE TITLE
It does not work on iOS

### ISSUE THREAD

**Issue by 10eputzen** [arkon/ng-click-outside#39]
My function  (clickOutside)="hideContextMenu()" is triggered as soon as I let go of the button. 
It works fine on Windows or Android. 
I am using it in a PWA in Angular 6

**Comment by arkon** [comment]
I don't own any iOS devices, but #19 might help.

**Comment by 10eputzen** [comment]
Thanks, I will look into it.
In case you want to ever test your code in iOS:
https://appetize.io/

It is quite slow but better than nothing :)
