### ISSUE TITLE
Click outside with ng2-bootstrap datepicker

### ISSUE THREAD

**Issue by n-simoes-santos-alb** [arkon/ng-click-outside#4]
Hi, i'm developing a component using ng2-bootstrap datepicker, but when i click on the month button the click-outside event is triggered!
I make this plunker: https://embed.plnkr.co/xXt9wKs7jzpaivQeLjbx/

Thanks,
NS

**Comment by arkon** [comment]
This is kind of a tough problem to solve. 

Let me lay down the problem:
- Whenever we click somewhere, we check if whatever we clicked is inside the element with the `clickOutside` directive, and handle it accordingly
- In the case of the datepicker, we're clicking a button that switches it to the month mode. Internally, this actually removes the date mode and replaces it with the month mode, meaning that the button we clicked is technically no longer there. So... technically, we _did_ click outside of it?

I feel like the datepicker itself needs to be modified to handle a click outside event.

**Comment by ostapch** [comment]
I have the same problem. Thanks for explanation why it happens

**Comment by Schim9** [comment]
Good morning,

I have the same issue with primeng datepicker component (p-schedule directive)
If someone could provide us with a work around?
 Thanks ^^

Eric

**Comment by tommueller** [comment]
+1

No solution for this so far?

**Comment by arkon** [comment]
The only thing I can think of is to toggle a flag when directly clicking the element with the directive on it, then checking it again once it propagates up to the body (where the click outside event will be triggered as needed). The only issue is that I cannot ensure that my click event happens before another one, so if clicking on something first triggers something to be removed (like the datepicker), then it doesn't really matter.

**Comment by tommueller** [comment]
Well I use the classic "transparent overlay"-workaround for the time being. That catches the outside click for the datepicker-popup, which is not pretty, but the best I could think of so far ...

**Comment by arkon** [comment]
I _think_ #13 might be related to this. `[delayClickOutsideInit]` might fix this, but I'm not really sure since I haven't tested it with the ng2-bootstrap datepicker myself.
