### ISSUE TITLE
delayClickOutsideInit not working

### ISSUE THREAD

**Issue by pedrollmatias** [arkon/ng-click-outside#40]
I'm trying to use the directive to handle clicks outside images in a gallery. In my scenario, when user clicks on the image, it creates a overlay in the image. The problem is that when the overlay is active and the user clicks in this image/overlay, the directive detect as an outside click. I tried to use  `[delayClickOutsideInit]="true"`, but didn't work. Here is my code:

```
<a  [ngClass]="['position-relative m-2 cursor-pointer',
	                 isSelectedImage(image) ? 'img-library-selected' : '']" 
			*ngFor="let image of images; let i = index"
			(click)="onImageClick($event, image, i)"
			(clickOutside)="clickOutsideImage($event)"
			[exclude]="'.img-library-overlay, .img-library-overlay-text'"
			[delayClickOutsideInit]="true">
      <img class="d-block img-library" src="{{image.link}}">
      <div *ngIf="isSelectedImage(image)">
            <div class="img-library-overlay"></div>
	    <div class="img-library-overlay-text">
		  <span>Selected</span>
            </div>
      </div>	
</a>
```

I also tried to set `excludeBeforeClick` to true, but without success. Am I doing it in the right way?

**Comment by rothsandro** [comment]
I had similar problems using the directive in the following HTML structure (simplified):

```
<div (clickOutside)="...">
  <div *ngIf="...">
    <div *customStructuralDirective="...">
      <div *ngIf="..."></div>
    </div>
  </div>
</div>
```

I don't know why this is happening but the solution was to remove the most inner *ngIf and just hide this element instead using a binding to the hidden attribute:

```
<div (clickOutside)="...">
  <div *ngIf="...">
    <div *customStructuralDirective="...">
      <div [hidden]="..."></div>
    </div>
  </div>
</div>
```

The drawback of this solution is that the element will not be removed from the DOM. It's not a problem until you have many elements ore bindings inside the *ngIf / hidden element.

**Comment by pedrollmatias** [comment]
Some weeks trying to find a better solution without use hidden attribute, but I failed. However, hidden atributte is enough for me. Thanks for your help.
