### ISSUE TITLE
exclude not working?

### ISSUE THREAD

**Issue by ganySA** [arkon/ng-click-outside#41]
i cannot seem to make exclude work?

Does this work with blur?

**Comment by arkon** [comment]
Not sure what you mean. A blur event isn't necessarily because of a click.

**Comment by ganySA** [comment]
Hi

When I use the exclude feature on a div class I expect it not to fire if I click on that div it does however still fire...

**Comment by arkon** [comment]
Can you post your relevant code?

**Comment by ganySA** [comment]
Hi

Hard to post full version but i have the following on one of my components:

[emitOnBlur]="true" [exclude]="'.popupContainer,.bubble'"  (clickOutside)="onClickedOutside($event)" 

however when i click on .popupContainer or .bubble it still fires clickOutside which then actually hides the popupcontainer..

**Comment by arkon** [comment]
What's the structure of the elements (`.popupContainer`, `.bubble`, the element with the directive)?

**Comment by yherasymchukarchitech** [comment]
I have the issue when elements in` [exclude]` array have style `position: absolute`

**Comment by ipsjolly** [comment]
Exclude not working:

    <div class="myPage">
        <div class="myBox" 
        (clickOutside)="onClickedOutside($event)" 
        *ngIf="isBoxVisible"
        [exclude]="'button,.show-again-btn'"
        [excludeBeforeClick]="true"
        >
        Click outside this box to hide
      </div>
      <button  
            (click)="showBox()" 
            *ngIf="!isBoxVisible"
            class="show-again-btn"
            >
        Click to show Box again
    </button>
    </div>

In class

  onClickedOutside(e) {
    this.isBoxVisible = false;
    console.log(e);
  }

  showBox() {
    this.isBoxVisible = true;
  }
