### ISSUE TITLE
How to use it properly with popup?

### ISSUE THREAD

**Issue by dgroh** [arkon/ng-click-outside#42]
I'm trying to use the `ng-click-outside` directive, but it does not work.

It's a popup and when I click outside of the popup it should close the popup. The problem is, that when I click in the document to show the popup it triggers already the outsideClick event. How do I avoid this event to be triggered when my popup first opens?

This is my component:

```
<div id="template" (clickOutside)="clickOutside($event)" [style.visibility]="isVisible ? 'visible' : 'hidden'">
    <ng-content></ng-content>
</div>
```

```
  showPopup(): void {
    this._isVisible = true;
  }

  clickOutside(e: Event) {
    this._isVisible = false;
  }
```

The **clickOutside** event is triggered just after **showPopup** which causes the popup to close automatically.

**Comment by dgroh** [comment]
That was my solution, but smells IMO

```
 showPopup(): void {
    this._active = true;
    this._isVisible = true;
  }

  clickOutside(e: Event) {
    if (!this._active) {
      this._isVisible = false;
    }

    this._active = false;
  }
```

**Comment by arkon** [comment]
Try using `[delayClickOutsideInit]="true"`.

**Comment by dgroh** [comment]
It does not work either.

I think (not sure) the problem is because the popup is already in the DOM as I'm using `visibility` instead of `*ngIf`. Makes sense?

**Comment by arkon** [comment]
Ah, that makes sense. You could try `[clickOutsideEnabled]="isVisible"`.

**Comment by Presiana** [comment]
Try excluding the popup trigger
