### ISSUE TITLE
Performance issue with querySelectorAll in excludeCheck

### ISSUE THREAD

**Issue by MohanPurushothaman** [arkon/ng-click-outside#45]
Our application which has more DOM nodes (approx 400,000-600,000 nodes) loaded in the browser.
Whenever user clicks any event, app takes around 6-8 seconds to triggered the event.
On monitoring the app performance via chrome dev tool, found that **ng-click-outside** is taking more time before calling the event.

**querySelectorAll in excludeCheck is taking more time to respond.**
Any suggestion to improve ?
![ng-click-perf issue](https://user-images.githubusercontent.com/43738938/46271927-77b09080-c56c-11e8-877d-53e74818ba00.PNG)

**Comment by manju-reddys** [comment]
Use virtual rendering (aka lazy rendering). not just this library but any other events on your page takes long to respond when you have so many node's.
