### ISSUE TITLE
doesnt work when clicked on body

### ISSUE THREAD

**Issue by sandgupta23** [arkon/ng-click-outside#48]
clickOutside doesn't trigger when clicked on body.

For example in following code i have attached clickOutside to div. Now if i click outside of `app-root` clickOutside wont trigger.

```
<app-root style="display: block">
  <div style="height: 200px; width: 200px; border: 1px solid red">
        <button (clickOutside)="onClickedOutside($event)">Normal</button>
        clickOutside will only work with this box
    </div>
<app-root>
```

Here is link to github [repo](https://github.com/goodmite/bootloader-not-working)

I tried to create a [stackblitz ](https://stackblitz.com/github/goodmite/bootloader-not-working) but in stackblitz clickOutside is not working at all. Weird.

**Comment by arkon** [comment]
Is your body's height actually set to take up more room then its contents?

**Comment by sandgupta23** [comment]
Hey, I will get back to you in few days.
