### ISSUE TITLE
clickOutsideEnabled doesn't work

### ISSUE THREAD

**Issue by paulinekorkina** [arkon/ng-click-outside#50]
Looks like `clickOutsideEnabled` doesn't work. This is my code:
```
<div
      (clickOutside)="onClickedOutside($event)"
      clickOutsideEnabled=false
>My element</div>
```
But `onClickedOutside` function is still triggered on outside click.

**Comment by arkon** [comment]
Try `[clickOutsideEnabled]="false"`.

**Comment by paulinekorkina** [comment]
> 
> 
> Try `[clickOutsideEnabled]="false"`.

It works, thank you so much!
