### ISSUE TITLE
Add support for Angular Ivy

### ISSUE THREAD

**Issue by euangoddard** [arkon/ng-click-outside#53]
I'm trying to upgrade a project to try out the Angular Ivy compiler and I'm getting an error from this package:

`ERROR in There is no format with import statements in '/xxx/node_modules/ng-click-outside' entry-point.`

Looking around, it looks like other package maintainers have found this: https://github.com/angular/angular/issues/29564

It appears this is related to the way the library is packaged. If you can advise I can attempt to make a PR, but I'm not too familiar with packaging Angular libraries

**Comment by arkon** [comment]
Supposedly fixed with Angular 8.2.0-next.0

https://github.com/angular/angular/issues/29564
