### ISSUE TITLE
Doesn't work properly if body is smaller than viewport

### ISSUE THREAD

**Issue by alexanium-dev** [arkon/ng-click-outside#57]
I have a page that does not fill the entire viewport, and there is an insensitive (to outside clicks) area at the bottom of viewport.

Why do you add listeners to `document.body` instead of `document`?

**Comment by arkon** [comment]
> I have a page that does not fill the entire viewport

But why? 

> Why do you add listeners to `document.body` instead of `document`?

No particular reason, I could change it.

**Comment by alexanium-dev** [comment]
> But why?

Because a screen is larger than a content of a page.

> No particular reason, I could change it.

Thank you. This fix is better for me than a CSS quirk:
``` CSS
html { height: 100%; }
body { min-height: 100%; }
```
