### ISSUE TITLE
This library adds ~400KB to my production build

### ISSUE THREAD

**Issue by johnmckay-reward** [arkon/ng-click-outside#58]
Hi folks. This directive works really well, but this library around 400KB to my production build!

I was able to save 400KB by literally taking the directive itself and adding it directly to my codebase (and removing it from package.json etc).

I'm using Angular 8.2.11.

Thanks

**Comment by arkon** [comment]
I'm not entirely sure what to say. Is there a way for you analyze your bundles (e.g. https://www.npmjs.com/package/webpack-bundle-analyzer) to see why? 

The build artifacts themselves are very basic.
