### ISSUE TITLE
clickOutside- differentiating drag from click

### ISSUE THREAD

**Issue by vinayakbkulkarni** [arkon/ng-click-outside#66]
The default behaviour shows click & drag to outside both trigger callback registered with clickOutside.
I need the event to be triggered only on click & not drag. How to achieve this

**Comment by arkon** [comment]
This is similar to #49.  You can maybe adjust which events are listened to instead?

**Comment by vinayakbkulkarni** [comment]
works well thanks. Added below suggested code
[clickOutsideEvents]="'mousedown'"

**Comment by vinayakbkulkarni** [comment]
but this now requires 2 clicks to get the clickOutside event. Is there any better approach which will make single click outside work.

**Comment by arkon** [comment]
No, this is just the browser's behaviour.

**Comment by vinayakbkulkarni** [comment]
I was just checking Gmail search dropdown which worked well. Is there any suggestion or alternate approach to adapt.

**Comment by arkon** [comment]
You can read the source code to get a better idea of what it's doing, but it's very basic usage of click handlers and checking what the target was.

If you have a better idea, feel free to suggest it.
