### ISSUE TITLE
ERROR in ClickOutsideModule is not an NgModule

### ISSUE THREAD

**Issue by pixelit** [arkon/ng-click-outside#7]
I get this error in my app since updating angular to 2.4.1 and the angular-cli to v1.0.0-beta.24:
"ERROR in ClickOutsideModule is not an NgModule"

I tried your module with a blank new anuglar-cli project and I get the same error when using ng serve. Trying ng serve -aot I get:

ERROR in Unexpected value 'ClickOutsideModule in /node_modules/ng-click-outside/lib/click-outside.module.d.ts' imported by the module 'AppModule in /src/app/app.module.ts'

**Comment by arkon** [comment]
@pixelit What version of TypeScript are you using?

Note to self, this seems relevant: https://github.com/angular/angular-cli/issues/3426

**Comment by pixelit** [comment]
tsv -v shows me 2.0.7 in my angular-cli test project

**Comment by bijujoseph** [comment]
@arkon is it possible to downgrade your  Typescript version to "2.0.x" ? As per [this](https://github.com/angular/angular-cli/issues/3426#issuecomment-268958876) comment angular-cli (or even angular2) is not fully ready for typescript 2.1.x.

**Comment by arkon** [comment]
@bijujoseph Whoops, yeah. I published v2.0.2 of the package which uses TS 2.0.10.

**Comment by pixelit** [comment]
**Thanks for the help!** Version 2.0.2 works in both my app and the angular-cli test app. Many thanks again. This was the last part of the puzzle to make AOT work for my app.
