### ISSUE TITLE
Angular 11: Please add a @NgModule annotation error when adding ClickOutsideModule to imports  

### ISSUE THREAD

**Issue by YazeedFares** [arkon/ng-click-outside#74]
We are using Angular 11 and getting the following error when importing the ClickOutsideModule

Error: Unexpected value 'ClickOutsideModule in /...../node_modules/ng-click-outside/lib_commonjs/click-outside.module.d.ts' imported by the module 'SomeModule in /.../SomeModule.module.ts'. Please add a @NgModule annotation.

Any idea?

**Comment by arkon** [comment]
I don't actively maintain this anymore, but it's because the library isn't compiled with Angular 11.

**Comment by shuZro** [comment]
> I don't actively maintain this anymore, but it's because the library isn't compiled with Angular 11.

Will you be fixing this?

**Comment by shuZro** [comment]
> We are using Angular 11 and getting the following error when importing the ClickOutsideModule
> 
> Error: Unexpected value 'ClickOutsideModule in /...../node_modules/ng-click-outside/lib_commonjs/click-outside.module.d.ts' imported by the module 'SomeModule in /.../SomeModule.module.ts'. Please add a @NgModule annotation.
> 
> Any idea?

Were you able to find a workaround?

**Comment by tobo37** [comment]
Use Version 7.0.0. It Works with Angular 11

**Comment by voidless-03** [comment]
The issue is when including this library and building with ng-packagr. The fix is to disable ivy in the angularCompilerOptions
