### ISSUE TITLE
Unable to upgrade from 7.0.0 to 7.0.1 with Angular 9.1.13

### ISSUE THREAD

**Issue by serenecloud** [arkon/ng-click-outside#76]
`npm outdated` has flagged `ng-click-outside` as needing an update to 7.0.1 on our project:

```
Package                             Current    Wanted    Latest  Location                                        Depended by
ng-click-outside                      7.0.0     7.0.1       7.0.1    node_modules/ng-click-outside    frontend
```

Attempting to update raises a dependency error with Angular 9 being too old.

```
$ npm update ng-click-outside
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend-build@2.0.0
npm ERR! Found: @angular/common@9.1.13
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~9.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=10.0.0" from ng-click-outside@7.0.1
npm ERR! node_modules/ng-click-outside
npm ERR!   ng-click-outside@"^7.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It looks like the `package-lock.json` file on `ng-click-outside` now requires Angular 10 (up from 8). Is this something that could be changed and dropped down to 9?

**Comment by arkon** [comment]
I'm not sure I understand, 7.0.0 bumped it up to Angular 10, not 7.0.1. How did you have 7.0.0 installed?

It's also worth mentioning that the lock file isn't part of the distributed tarball, nor are dependency's lock files used when resolving its dependencies anyway (at least with `npm`, AFAIK).

EDIT: If you're using Angular 9, you'll need to use the last version of the library that supported that, which would be 6.0.0.

**Comment by serenecloud** [comment]
Hey, thanks for the quick reply and the detailed answer. I didn't realise it was the 7.0.0 release which removed Angular 9 support but it's a sensible thing to change in a major version.

I'm not sure how this project installed 7.0.0 it but I'll follow up with the developer who added it and see if we look at downgrading to the 6.x branch until we upgrade Angular.
