### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by BahKoo** [arkon/ng-click-outside#8]
The peerDependencies for @angular/core and @angular/platform-browse cause "UNMET PEER DEPENDENCY" when using npm to install ng-click-outside alongside version 4 of the angular libraries. 

Can these peerDependencies but updated to version ^4.0.0?

**Comment by arkon** [comment]
Fixed via 48275dbf6e6812088ebe3ffee07d0248a96b5b9d. v2.0.3 published to NPM with this.
